inhibit_all_warnings!

target "iOS Tests" do
platform :ios, '5.0' 
  pod 'Kiwi/XCTest', '2.2.4'
  pod 'CMFactory', '1.4.1'
  pod 'MagicalRecord'
end

target "OS X Tests" do
platform :osx, '10.8'

  pod 'Kiwi/XCTest', '2.2.4'
  pod 'CMFactory', '1.4.1'
  pod 'MagicalRecord'
end





