platform :ios, :deployment_target => "6.0"
inhibit_all_warnings!

target :EasyMappingExample do
  pod 'MagicalRecord'
end

target :EasyMappingExampleTests do
  pod 'Kiwi', '2.2.4'
  pod 'CMFactory', '1.3.1'
end





