fastlane_version "1.98.0"

lane :test_ios10 do
  scan(devices: ["iPhone 7 (10.3)"])
end

lane :test_ios9 do
  scan(devices: ["iPhone 6s (9.3)"])
end

lane :test_tvos10 do
  scan(device: "Apple TV 1080p (10.2)")
end

lane :test_macos do
  scan(destination: "arch=x86_64")
end

lane :build_watchos do
  xcodebuild(
    build: true,
    destination: "OS=3.2,name=Apple Watch - 42mm"
  )
end

lane :carthage_build do
  carthage(command: "build", no_skip_current: true, verbose: true)
end

lane :spm_macos do
  sh "swift build"
end
