platform :ios, :deployment_target => "5.0"

pod 'MagicalRecord'

target :EasyMappingCoreDataExampleTests, :exclusive => true do
  pod 'Kiwi', '2.0.5'
  pod 'CMFactory', '1.2.0'
  pod 'MagicalRecord'
end
